import { useState, useEffect } from "react";

// Language & Agent Data
const languages = {
  Hindi: {
    greet: "Bhai, main aapke liye code likh rahi hoon!",
    placeholder: "Prompt dalo...",
    build: "BANAO 🚀",
    deploy: "LIVE KARO",
  },
  English: {
    greet: "I'm writing the code for you!",
    placeholder: "Type a prompt...",
    build: "BUILD 🚀",
    deploy: "GO LIVE",
  },
  Marathi: {
    greet: "मी तुमच्यासाठी कोड लिहित आहे!",
    placeholder: "प्रॉम्प्ट टाका...",
    build: "बनवा 🚀",
    deploy: "लाईव्ह करा",
  },
  Bengali: {
    greet: "আমি আপনার জন্য কোড লিখছি!",
    placeholder: "প্রম্পট দিন...",
    build: "তৈরি করুন 🚀",
    deploy: "লাইভ করুন",
  },
} as const;

const agentNames = {
  India: {
    name: "Maya",
    theme: "linear-gradient(135deg, #0d1117 0%, #161b22 100%)",
  },
  USA: {
    name: "Mia",
    theme: "linear-gradient(135deg, #001f3f 0%, #000000 100%)",
  },
  Japan: {
    name: "Yuki",
    theme: "linear-gradient(135deg, #2d1b2d 0%, #1a0f1a 100%)",
  },
} as const;

type LangKey = keyof typeof languages;
type CountryKey = keyof typeof agentNames;

export default function App() {
  const [code, setCode] = useState<string>(
    "\n<div style='text-align:center; padding:50px; font-family:sans-serif;'>\n  <h1>Welcome to Global AI Builder</h1>\n  <p>Prompt dalo aur magic dekho!</p>\n</div>",
  );
  const [prompt, setPrompt] = useState<string>("");
  const [lang, setLang] = useState<LangKey>("Hindi");
  const [country, setCountry] = useState<CountryKey>("India");
  const [activeTab, setActiveTab] = useState<"editor" | "preview">("editor");
  const [isDeploying, setIsDeploying] = useState<boolean>(false);
  const [isMobile, setIsMobile] = useState<boolean>(
    typeof window !== "undefined" ? window.innerWidth < 768 : false,
  );

  useEffect(() => {
    const handleResize = () => setIsMobile(window.innerWidth < 768);
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  // The Super Brain (Templates + Logic)
  const handleMayaAction = () => {
    if (!prompt) return;
    const p = prompt.toLowerCase();
    let res = "";

    if (p.includes("calculator")) {
      const buttons = [
        "7",
        "8",
        "9",
        "/",
        "4",
        "5",
        "6",
        "*",
        "1",
        "2",
        "3",
        "-",
        "0",
        "C",
        "=",
        "+",
      ];
      res = `<div style="max-width:300px; margin:20px auto; background:#222; padding:20px; border-radius:20px; font-family:sans-serif; color:white; text-align:center;">
  <div style="background:#000; padding:20px; font-size:24px; text-align:right; border-radius:10px; margin-bottom:10px;">0</div>
  <div style="display:grid; grid-template-columns:repeat(4, 1fr); gap:10px;">
    ${buttons.map((b) => `<button style="padding:15px; background:#444; color:white; border:none; border-radius:10px;">${b}</button>`).join("")}
  </div>
</div>`;
    } else if (p.includes("netflix") || p.includes("movie")) {
      res = `<body style="background:#000; color:white; font-family:sans-serif; margin:0;">
  <nav style="padding:20px; font-size:24px; color:red; font-weight:bold;">MAYAFLIX</nav>
  <div style="padding:20px;">
    <h2>Trending Now</h2>
    <div style="display:flex; gap:10px; overflow-x:auto;">
      ${[1, 2, 3, 4].map((i) => `<div style="min-width:150px; height:220px; background:#333; border-radius:10px; display:flex; align-items:center; justify-content:center;">Movie ${i}</div>`).join("")}
    </div>
  </div>
</body>`;
    } else if (p.includes("weather")) {
      res = `<div style="max-width:300px; margin:20px auto; background:linear-gradient(to bottom, #58a6ff, #1f6feb); padding:30px; border-radius:20px; color:white; font-family:sans-serif; text-align:center;">
  <h2>Bhopal</h2>
  <div style="font-size:60px; margin:10px 0;">32°C</div>
  <p>Sunny Day</p>
</div>`;
    } else {
      res = `<div style="padding:40px; text-align:center; font-family:sans-serif; background:#f0f0f0; border-radius:20px;">
  <h1>${prompt}</h1>
  <p>Generated by ${agentNames[country].name} AI</p>
</div>`;
    }

    setCode(res);
    setPrompt("");
    if (isMobile) setTimeout(() => setActiveTab("preview"), 400);
  };

  const copyCode = () => {
    navigator.clipboard.writeText(code);
    alert("Code Copied!");
  };  const shareSite = () => {
    const encoded = btoa(code); 
    const shareUrl = `${window.location.origin}${window.location.search.includes('?') ? window.location.search + '&' : '?'}site=${encoded}`;
    const message = `Bhai, dekh maine Maya AI se ye website banayi hai! Link khol ke check kar: ${shareUrl}`;
    const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(whatsappUrl, '_blank');
  };


  const deployToNetlify = () => {
    if (isDeploying) return;
    setIsDeploying(true);
    setTimeout(() => {
      setIsDeploying(false);
      const liveUrl =
        typeof window !== "undefined" ? window.location.origin : "";
      if (liveUrl) {
        window.open(liveUrl, "_blank", "noopener,noreferrer");
      }
    }, 800);
  };

  return (
    <div
      style={{
        display: "flex",
        flexDirection: isMobile ? "column" : "row",
        height: "100vh",
        background: agentNames[country].theme,
        color: "#c9d1d9",
        overflow: "hidden",
      }}
    >
      {/* SIDEBAR */}
      <div
        style={{
          width: isMobile ? "100%" : "320px",
          background: "rgba(22, 27, 34, 0.95)",
          padding: "20px",
          borderRight: "1px solid #30363d",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            marginBottom: "15px",
          }}
        >
          <select
            value={country}
            onChange={(e) => setCountry(e.target.value as CountryKey)}
            style={{
              background: "#010409",
              color: "#fff",
              border: "none",
              borderRadius: "5px",
              padding: "5px",
              fontSize: "12px",
            }}
          >
            {(Object.keys(agentNames) as CountryKey[]).map((c) => (
              <option key={c} value={c}>
                {c}
              </option>
            ))}
          </select>
          <select
            value={lang}
            onChange={(e) => setLang(e.target.value as LangKey)}
            style={{
              background: "#010409",
              color: "#fff",
              border: "none",
              borderRadius: "5px",
              padding: "5px",
              fontSize: "12px",
            }}
          >
            {(Object.keys(languages) as LangKey[]).map((l) => (
              <option key={l} value={l}>
                {l}
              </option>
            ))}
          </select>
        </div>

        <div style={{ textAlign: "center", marginBottom: "20px" }}>
          <div
            style={{
              width: "60px",
              height: "60px",
              borderRadius: "50%",
              background: "linear-gradient(45deg, #ff7b72, #8957e5)",
              margin: "0 auto 10px",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontSize: "30px",
            }}
          >
            👩‍💼
          </div>
          <h3 style={{ color: "#58a6ff", margin: 0 }}>
            {agentNames[country].name} AI
          </h3>
          <p style={{ fontSize: "11px", color: "#8b949e" }}>
            {languages[lang].greet}
          </p>
        </div>

        <div style={{ flex: 1 }}>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder={languages[lang].placeholder}
            style={{
              width: "100%",
              height: "80px",
              background: "#010409",
              border: "1px solid #30363d",
              borderRadius: "8px",
              color: "#fff",
              padding: "10px",
              resize: "none",
              marginBottom: "10px",
              boxSizing: "border-box",
            }}
          />
          <button
            onClick={handleMayaAction}
            style={{
              width: "100%",
              padding: "12px",
              background: "#238636",
              border: "none",
              borderRadius: "8px",
              color: "white",
              fontWeight: "bold",
              marginBottom: "10px",
              cursor: "pointer",
            }}
          >
            {languages[lang].build}
          </button>
          <button
            onClick={deployToNetlify}
            style={{
              width: "100%",
              padding: "12px",
              background: "#1f6feb",
              border: "none",
              borderRadius: "8px",
              color: "white",
              fontWeight: "bold",
              opacity: isDeploying ? 0.6 : 1,
              cursor: "pointer",
            }}
          >
            {isDeploying ? "Deploying..." : languages[lang].deploy}
          </button>
        </div>
      </div>

      {/* EDITOR & PREVIEW */}
      <div
        style={{
          flex: 1,
          display: "flex",
          flexDirection: "column",
          overflow: "hidden",
        }}
      >
        <div
          style={{
            padding: "10px 20px",
            background: "#161b22",
            borderBottom: "1px solid #30363d",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <div style={{ display: "flex", gap: "5px" }}>
            {isMobile && (
              <button
                onClick={() =>
                  setActiveTab(activeTab === "editor" ? "preview" : "editor")
                }
                style={{
                  background: "#30363d",
                  color: "white",
                  border: "none",
                  padding: "5px 15px",
                  borderRadius: "5px",
                  fontSize: "12px",
                  cursor: "pointer",
                }}
              >
                {activeTab === "editor" ? "Preview" : "Code"}
              </button>
            )}
          </div>
          <button
            onClick={copyCode}
            style={{
              background: "#21262d",
              color: "#c9d1d9",
              border: "1px solid #30363d",
              padding: "5px 15px",
              borderRadius: "6px",
              fontSize: "12px",
              cursor: "pointer",
            }}
          >
            Copy Code
          </button>
        </div>
<button 
  onClick={shareSite} 
  style={{ 
    background: '#238636', 
    color: 'white', 
    border: 'none', 
    padding: '5px 15px', 
    borderRadius: '6px', 
    fontSize: '12px', 
    marginLeft: '8px',
    cursor: 'pointer' 
  }}
>
  WhatsApp Share 📱
</button>
        
        <div style={{ display: "flex", flex: 1, overflow: "hidden" }}>
          {(!isMobile || activeTab === "editor") && (
            <textarea
              value={code}
              onChange={(e) => setCode(e.target.value)}
              style={{
                flex: 1,
                background: "#0d1117",
                color: "#79c0ff",
                padding: "20px",
                fontFamily: "monospace",
                border: "none",
                outline: "none",
                resize: "none",
                borderRight: !isMobile ? "1px solid #30363d" : "none",
              }}
            />
          )}
          {(!isMobile || activeTab === "preview") && (
            <iframe
              title="preview"
              srcDoc={code}
              style={{ flex: 1, background: "#fff", border: "none" }}
            />
          )}
        </div>
      </div>
    </div>
  );
}
